document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<div class=\'deng-box2\'>");
document.writeln("    <div class=\'deng\'>");
document.writeln("        <div class=\'xian\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'deng-a\'>");
document.writeln("            <div class=\'deng-b\'>");
document.writeln("                <div class=\'deng-t\'>年</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'shui shui-a\'>");
document.writeln("            <div class=\'shui-c\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'shui-b\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'deng-box3\'>");
document.writeln("    <div class=\'deng\'>");
document.writeln("        <div class=\'xian\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'deng-a\'>");
document.writeln("            <div class=\'deng-b\'>");
document.writeln("                <div class=\'deng-t\'>新</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'shui shui-a\'>");
document.writeln("            <div class=\'shui-c\'></div>");
document.writeln("            <div class=\'shui-b\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'deng-box1\'>");
document.writeln("    <div class=\'deng\'>");
document.writeln("        <div class=\'xian\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'deng-a\'>");
document.writeln("            <div class=\'deng-b\'>");
document.writeln("                <div class=\'deng-t\'>乐</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'shui shui-a\'>");
document.writeln("            <div class=\'shui-c\'></div>");
document.writeln("            <div class=\'shui-b\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'deng-box\'>");
document.writeln("    <div class=\'deng\'>");
document.writeln("        <div class=\'xian\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'deng-a\'>");
document.writeln("            <div class=\'deng-b\'>");
document.writeln("                <div class=\'deng-t\'>快</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'shui shui-a\'>");
document.writeln("            <div class=\'shui-c\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'shui-b\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<style type=\'text/css\'>");
document.writeln("    .deng-box {");
document.writeln("        position: fixed;");
document.writeln("        top: -40px;");
document.writeln("        right: 150px;");
document.writeln("        z-index: 9999;");
document.writeln("        pointer-events: none;");
document.writeln("    }");
document.writeln("    .deng-box1 {");
document.writeln("        position: fixed;");
document.writeln("        top: -30px;");
document.writeln("        right: 10px;");
document.writeln("        z-index: 9999;");
document.writeln("        pointer-events: none");
document.writeln("    }");
document.writeln("    .deng-box2 {");
document.writeln("        position: fixed;");
document.writeln("        top: -40px;");
document.writeln("        left: 150px;");
document.writeln("        z-index: 9999;");
document.writeln("        pointer-events: none");
document.writeln("    }");
document.writeln("    .deng-box3 {");
document.writeln("        position: fixed;");
document.writeln("        top: -30px;");
document.writeln("        left: 10px;");
document.writeln("        z-index: 9999;");
document.writeln("        pointer-events: none");
document.writeln("    }");
document.writeln("    .deng-box1 .deng,");
document.writeln("    .deng-box3 .deng {");
document.writeln("        position: relative;");
document.writeln("        width: 120px;");
document.writeln("        height: 90px;");
document.writeln("        margin: 50px;");
document.writeln("        background: #d8000f;");
document.writeln("        background: rgba(216, 0, 15, .8);");
document.writeln("        border-radius: 50% 50%;");
document.writeln("        -webkit-transform-origin: 50% -100px;");
document.writeln("        -webkit-animation: swing 5s infinite ease-in-out;");
document.writeln("        box-shadow: -5px 5px 30px 4px #fc903d");
document.writeln("    }");
document.writeln("    .deng {");
document.writeln("        position: relative;");
document.writeln("        width: 120px;");
document.writeln("        height: 90px;");
document.writeln("        margin: 50px;");
document.writeln("        background: #d8000f;");
document.writeln("        background: rgba(216, 0, 15, .8);");
document.writeln("        border-radius: 50% 50%;");
document.writeln("        -webkit-transform-origin: 50% -100px;");
document.writeln("        -webkit-animation: swing 3s infinite ease-in-out;");
document.writeln("        box-shadow: -5px 5px 50px 4px #fa6c00");
document.writeln("    }");
document.writeln("    .deng-a {");
document.writeln("        width: 100px;");
document.writeln("        height: 90px;");
document.writeln("        background: #d8000f;");
document.writeln("        background: rgba(216, 0, 15, .1);");
document.writeln("        margin: 12px 8px 8px 8px;");
document.writeln("        border-radius: 50% 50%;");
document.writeln("        border: 2px solid #dc8f03");
document.writeln("    }");
document.writeln("    .deng-b {");
document.writeln("        width: 45px;");
document.writeln("        height: 90px;");
document.writeln("        background: #d8000f;");
document.writeln("        background: rgba(216, 0, 15, .1);");
document.writeln("        margin: -4px 8px 8px 26px;");
document.writeln("        border-radius: 50% 50%;");
document.writeln("        border: 2px solid #dc8f03");
document.writeln("    }");
document.writeln("    .xian {");
document.writeln("        position: absolute;");
document.writeln("        top: -20px;");
document.writeln("        left: 60px;");
document.writeln("        width: 2px;");
document.writeln("        height: 20px;");
document.writeln("        background: #dc8f03");
document.writeln("    }");
document.writeln("    .shui-a {");
document.writeln("        position: relative;");
document.writeln("        width: 5px;");
document.writeln("        height: 20px;");
document.writeln("        margin: -5px 0 0 59px;");
document.writeln("        -webkit-animation: swing 4s infinite ease-in-out;");
document.writeln("        -webkit-transform-origin: 50% -45px;");
document.writeln("        background: orange;");
document.writeln("        border-radius: 0 0 5px 5px");
document.writeln("    }");
document.writeln("    .shui-b {");
document.writeln("        position: absolute;");
document.writeln("        top: 14px;");
document.writeln("        left: -2px;");
document.writeln("        width: 10px;");
document.writeln("        height: 10px;");
document.writeln("        background: #dc8f03;");
document.writeln("        border-radius: 50%");
document.writeln("    }");
document.writeln("    .shui-c {");
document.writeln("        position: absolute;");
document.writeln("        top: 18px;");
document.writeln("        left: -2px;");
document.writeln("        width: 10px;");
document.writeln("        height: 35px;");
document.writeln("        background: orange;");
document.writeln("        border-radius: 0 0 0 5px");
document.writeln("    }");
document.writeln("    .deng:before {");
document.writeln("        position: absolute;");
document.writeln("        top: -7px;");
document.writeln("        left: 29px;");
document.writeln("        height: 12px;");
document.writeln("        width: 60px;");
document.writeln("        content: \' \';");
document.writeln("        display: block;");
document.writeln("        z-index: 999;");
document.writeln("        border-radius: 5px 5px 0 0;");
document.writeln("        border: solid 1px #dc8f03;");
document.writeln("        background: orange;");
document.writeln("        background: linear-gradient(to right, #dc8f03, orange, #dc8f03, orange, #dc8f03)");
document.writeln("    }");
document.writeln("    .deng:after {");
document.writeln("        position: absolute;");
document.writeln("        bottom: -7px;");
document.writeln("        left: 10px;");
document.writeln("        height: 12px;");
document.writeln("        width: 60px;");
document.writeln("        content: \' \';");
document.writeln("        display: block;");
document.writeln("        margin-left: 20px;");
document.writeln("        border-radius: 0 0 5px 5px;");
document.writeln("        border: solid 1px #dc8f03;");
document.writeln("        background: orange;");
document.writeln("        background: linear-gradient(to right, #dc8f03, orange, #dc8f03, orange, #dc8f03)");
document.writeln("    }");
document.writeln("    .deng-t {");
document.writeln("        font-size:2rem;");
document.writeln("        color: #dc8f03;");
document.writeln("        font-weight: 700;");
document.writeln("        line-height: 85px;");
document.writeln("        text-align: center");
document.writeln("    }");
document.writeln("    .night .deng-box,");
document.writeln("    .night .deng-box1,");
document.writeln("    .night .deng-t {");
document.writeln("        background: 0 0 !important");
document.writeln("    }");
document.writeln("    @-moz-keyframes swing {");
document.writeln("        0% {");
document.writeln("            -moz-transform: rotate(-10deg)");
document.writeln("        }");
document.writeln("        50% {");
document.writeln("            -moz-transform: rotate(10deg)");
document.writeln("        }");
document.writeln("        100% {");
document.writeln("            -moz-transform: rotate(-10deg)");
document.writeln("        }");
document.writeln("    }");
document.writeln("    @-webkit-keyframes swing {");
document.writeln("        0% {");
document.writeln("            -webkit-transform: rotate(-10deg)");
document.writeln("        }");
document.writeln("        50% {");
document.writeln("            -webkit-transform: rotate(10deg)");
document.writeln("        }");
document.writeln("        100% {");
document.writeln("            -webkit-transform: rotate(-10deg)");
document.writeln("        }");
document.writeln("    }");
document.writeln("@media(max-width:960px){.deng-box,.deng-box1,.deng-box2,.deng-box3 {display: none!important;}}");
document.writeln("</style>");
