// 南通伍林堂文化传播有限公司版权所有
document.writeln("<style>");
document.writeln(".side-btns-wrap {");
document.writeln("	margin:0;");
document.writeln("	position:fixed;");
document.writeln("	top:80px;");
document.writeln("	z-index:9999;");
document.writeln("	width:120px;");
document.writeln("	left: 0;");
document.writeln("}");
document.writeln(".side-btns-wrap li,.side-btns-wrap .ft,.side-btns-wrap .hd {");
document.writeln("	text-align:right;");
document.writeln("	position:relative;");
document.writeln("	margin-bottom:1px;");
document.writeln("	vertical-align:bottom;");
document.writeln("	white-space:nowrap;");
document.writeln("	list-style-type: none;");
document.writeln("height: 35px;");
document.writeln("    max-height: 35px;");
document.writeln("}");
document.writeln(".side-btns-wrap li a,.side-btns-wrap .ft a {");
document.writeln("	color: #000!important;");
document.writeln("	display:inline-block;");
document.writeln("height: 35px;");
document.writeln("    line-height: 35px;");
document.writeln("	width:120px;");
document.writeln("	padding:0 5px;");
document.writeln("	overflow:hidden;");
document.writeln("	background:#fff;");
document.writeln("	text-align:right;");
document.writeln("	float:right;");
document.writeln("	text-align:center;");
document.writeln("}");
document.writeln(".side-btns-wrap li a:hover {");
document.writeln("	text-decoration:none;");
document.writeln("	background: #D14836;");
document.writeln("    background-position-y: bottom;");
document.writeln("    background-attachment: fixed;");
document.writeln("    background-size: 300px 533px;");
document.writeln("	color:#fff!important;");
document.writeln("}");
document.writeln(".side-btns-wrap li em {");
document.writeln("	font-style:normal;");
document.writeln("	padding:0 3px;");
document.writeln("}");
document.writeln(".side-btns-wrap li.act a {");
document.writeln("	background:#60c77e;");
document.writeln("}");
document.writeln(".side-btns-wrap li i {");
document.writeln("	display:block;");
document.writeln("	width:6px;");
document.writeln("	height:12px;");
document.writeln("	position:absolute;");
document.writeln("	left:-6px;");
document.writeln("	top:9px;");
document.writeln("	display:none;");
document.writeln("}");
document.writeln(".side-btns-wrap li.act i {");
document.writeln("	display:block;");
document.writeln("}");
document.writeln(".side-btns-wrap .ft a {");
document.writeln("	width:75px;");
document.writeln("	padding:0 5px 0 20px;");
document.writeln("}");
document.writeln(".side-btns-wrap .ft a:hover {");
document.writeln("	text-decoration:none;");
document.writeln("	background-color:#CCC;");
document.writeln("}");
document.writeln(".side-btns-wrap .hd {");
document.writeln("	margin-bottom:0px;");
document.writeln("	overflow:hidden;");
document.writeln("	width:100px;");
document.writeln("	cursor:pointer");
document.writeln("}");
document.writeln(".side-btns-wrap .hd span {");
document.writeln("	float:left;");
document.writeln("	padding:0 0 0 33px;");
document.writeln("	color:#666;");
document.writeln("	line-height:24px;");
document.writeln("}");
document.writeln("#feedAv{ margin-top: -250px!important;transform: scale(0);}");
document.writeln("@media(max-width:960px)");
document.writeln("{.side-btns-wrap{display:none}}");
document.writeln("</style>	");
document.writeln("<div class=\'side-btns-wrap\'>");
document.writeln("<ul id=\'k\'>");
document.writeln("<li id=\'k_1\'><a href=\'https://www.wulintang.cn/tz/live.php\' target=\'_blank\' rel=\'nofollow\' style=\'color: #ff0000!important ;\'><b>直播间</b></a></li> ");
document.writeln("<li id=\'k_1\'><a href=\'http://mp.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>小道号</a></li> ");
document.writeln("<li id=\'k_1\'><a href=\'https://www.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>云道家</a></li> ");
document.writeln("<li id=\'k_3\'><a href=\'https://www.daoyue.org\' target=\'_blank\' rel=\'nofollow\'>云道乐</a></li>");
document.writeln("<li id=\'k_4\'><a href=\'http://360.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>云道航</a></li>");
document.writeln("<li id=\'k_5\'><a href=\'https://www.chndao.com\' target=\'_blank\' rel=\'nofollow\'>云道商</a></li>");
document.writeln("<li id=\'k_8\'><a href=\'http://weibo.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>云道馆</a></li>");
document.writeln("<li id=\'k_6\'><a href=\'http://www.ccwadj.cn\' target=\'_blank\' rel=\'nofollow\'>云之道</a></li>");
document.writeln("<li id=\'k_7\'><a href=\'https://sou.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>云搜道</a></li>");
document.writeln("<li id=\'k_8\'><a href=\'https://meng.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>云解梦</a></li>");
document.writeln("<li id=\'k_9\'><a href=\'https://ggz.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>鬼谷子</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'http://www.dasu.net.cn\' target=\'_blank\' rel=\'nofollow\' style=\'color: #ff0000!important ;\'><b>大江苏</b></a></li>");
document.writeln("<li id=\'k_0\'><a href=\'http://www.yangtuo.live\' target=\'_blank\' rel=\'nofollow\' style=\'color: #ff0000!important ;\'><b>私人影院</b></a></li>");
document.writeln("<li id=\'k_0\'><a href=\'http://wiki.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>道教百科</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://www.zhtaoism.com\' target=\'_blank\' rel=\'nofollow\'>中网道研</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://www.chntaoism.com\' target=\'_blank\' rel=\'nofollow\'>兴汉联盟</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://miao.taoisms.org\' target=\'_blank\' rel=\'nofollow\'>遇真道观</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://www.lizhichen.cn\' target=\'_blank\' rel=\'nofollow\'>慈善公益</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://www.wulintang.cn\' target=\'_blank\' rel=\'nofollow\'>网站制作</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'http://www.it171.cn\' target=\'_blank\' rel=\'nofollow\'>站长社区</a></li>");
document.writeln("<li id=\'k_0\'><a href=\'https://朱楠.我爱你\' target=\'_blank\' rel=\'nofollow\'>朱楠我爱你</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
if (window.console) {
    var cons = console;
    if (cons) {
        cons.log("%c\n       ", "font-size:41px;background:url('https://1.taoisms.org/ad/logo.png') no-repeat -4px -4px");
cons.log('道教是中国唯一的土生土长的宗教，它是在汉朝末年创立的。');
cons.log('张道陵祖师创教后，多地多派为道教带来了和谐的自然规律。');
cons.log('在这里，请您敬请感受来自于大自然的道的气息于丰厚魅力。');
cons.log('而当你看到这段话的时候，你可知，我们一直在等你加入！');
cons.log('跟我们共创道教科技未来，请发送邮件至（jop@ccwadj.cn）在邮件中注明%c来自:console', 'color:red;font-weight:bold;' );
    }
  }