// 南通伍林堂文化传播有限公司 动次打次 App下载
document.writeln("<style>");
document.writeln(".margingT {");
document.writeln("	margin-bottom:100px;");
document.writeln("}");
document.writeln(".bottomAD {");
document.writeln("	-webkit-box-sizing:border-box;");
document.writeln("	height:100px;");
document.writeln("	position:fixed;");
document.writeln("	bottom:0;");
document.writeln("	left:0;");
document.writeln("	z-index:1000;");
document.writeln("	padding:0 10px;");
document.writeln("	overflow:hidden;");
document.writeln("	width:100%;");
document.writeln("	background:rgba(0,0,0,0.48);");
document.writeln("}");
document.writeln(".bottom-pic {");
document.writeln("	position:absolute;");
document.writeln("	margin-top:10px;");
document.writeln("	overflow:hidden;");
document.writeln("	border-radius:10px;");
document.writeln("	margin-left:200px;");
document.writeln("}");
document.writeln(".bottom-text {");
document.writeln("	line-height:80px;");
document.writeln("	font-size:32px;");
document.writeln("	color:#f4e0a7;");
document.writeln("	margin-top:10px;");
document.writeln("}");
document.writeln(".bottom-btn {");
document.writeln("	position:absolute;");
document.writeln("	top:32px;");
document.writeln("	right:300px;");
document.writeln("	height:40px;");
document.writeln("	line-height:40px;");
document.writeln("	color:#f4e0a7;");
document.writeln("	background-color:#D70D1C;");
document.writeln("	border-radius:6px;");
document.writeln("	text-align:center;");
document.writeln("	font-size:24px;");
document.writeln("	padding:0 5px;");
document.writeln("}");
document.writeln(".bottomAD a {");
document.writeln("	position:absolute;");
document.writeln("	top:0;");
document.writeln("	right:0;");
document.writeln("	bottom:0;");
document.writeln("	left:0;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\'bottomAD\' id=\'bottomAD\'>");
document.writeln("  <div class=\'bottom-con\'>");
document.writeln("    <div class=\'bottom-pic\'>");
document.writeln("      <img src=\'https://img.wulintang.cn/youhui/static/images/banenr-logo.png\' style=\'height: 65px;\'/></div>");
document.writeln("    <div class=\'bottom-text\' id=\'bottomText\'>动次打次APP-www.dongci.top 每日万款大额优惠券等你抢 , 海量优惠券</div>");
document.writeln("    <div class=\'bottom-btn\'>立即下载</div></div>");
document.writeln("  <a id=\'bottomLink\' href=\'https://www.wulintang.cn/download\'></a>");
document.writeln("</div>");