document.writeln("<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=http://www.sara.gov.cn/?lailu=wulintang.cn\' title=\'国家宗教事务局\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/guo.png\' alt=\'国家宗教事务局\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=http://www.taoist.org.cn/?lailu=wulintang.cn\' title=\'中国道教协会\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/dao.png\' alt=\'中国道教协会\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.yudao.org.cn/?lailu=wulintang.cn\' title=\'遇真道院\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/yu.png\' alt=\'遇真道院\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.wulintang.net/?lailu=wulintang.cn\' title=\'伍林堂安全应急响应中心\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/wu.png\' alt=\'伍林堂安全应急响应中心\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.zhtaoism.com/?lailu=wulintang.cn\' title=\'伍林堂道教事业发展部\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/wang.png\' alt=\'伍林堂道教事业发展部\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.taoisms.cn/?lailu=wulintang.cn\' title=\'盘龙阁权益保护委员会\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/pan.png\' alt=\'盘龙阁权益保护委员会\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.wulintang.net.cn/?lailu=wulintang.cn\' title=\'伍林堂百姓图文设计部\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/bai.png\' alt=\'伍林堂百姓图文设计部\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.hxwmzsf.com/?lailu=wulintang.cn\' title=\'昊國學宮中樞府\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ad/icon/hao.png\' alt=\'昊國學宮中樞府\'/></a>");
document.writeln("		</p>");
document.writeln("		<p class=\'tong\'>");
document.writeln("		<a href=\'https://www.wulintang.cn/new/go.php?url=https://www.chntaoism.com/?lailu=wulintang.cn\' title=\'伍林堂兴汉同盟企业合伙\' target=\'_blank\'>");
document.writeln("		<img src=\'https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjih