document.writeln("<div class=\'security-help-wrapper\'><div class=\'security-help\'><div class=\'sh-head\'><img src=\'https://www.wulintang.net/Public/Index/images/logo.png\'><span>安全漏洞<br>信息反馈</span></div><div class=\'sh-body\'><p>如果您发现伍林堂下属产品存在安全漏洞，欢迎将漏洞信息发送给<a target=\'_blank\'href=\'http://www.wulintang.net/\'><em>伍林堂安全应急响应中心</em></a></p></div></div></div>");
document.writeln("<style type=text/css>");
document.writeln(".common-footer .footer-copyright {");
document.writeln("	padding-bottom:20px;");
document.writeln("}");
document.writeln(".security-help-wrapper {");
document.writeln("	width:100%;");
document.writeln("	height:auto;");
document.writeln("	overflow:hidden;");
document.writeln("}");
document.writeln(".security-help {");
document.writeln("	width:calc(100% - 40px);");
document.writeln("	max-width:460px;");
document.writeln("	margin:0 auto;");
document.writeln("	padding-bottom:40px;");
document.writeln("	display:flex;");
document.writeln("	align-items:stretch;");
document.writeln("	justify-content:center;");
document.writeln("	color:#666;");
document.writeln("	font-size:13px;");
document.writeln("}");
document.writeln(".security-help .sh-head {");
document.writeln("	width:114px;");
document.writeln("	min-width:114px;");
document.writeln("	display:flex;");
document.writeln("	align-items:center;");
document.writeln("	justify-content:center;");
document.writeln("	padding:5px;");
document.writeln("	font-weight:bold;");
document.writeln("	color:#ffffff;");
document.writeln("	background-color:#0aad62;");
document.writeln("	border:1px solid #0aad62;");
document.writeln("	user-select:none;");
document.writeln("}");
document.writeln(".security-help .sh-head img {");
document.writeln("	width:28px;");
document.writeln("	min-width:28px;");
document.writeln("	margin-right:5px;");
document.writeln("	display:block;");
document.writeln("	height:auto;");
document.writeln("	white-space:nowrap;");
document.writeln("}");
document.writeln(".security-help .sh-body {");
document.writeln("	flex:1 1 auto;");
document.writeln("	align-items:center;");
document.writeln("	justify-content:center;");
document.writeln("	padding:8px 10px;");
document.writeln("	font-size:12px;");
document.writeln("	background-color:#fff;");
document.writeln("	border:1px solid #0aad62;");
document.writeln("	color:#0aad62;");
document.writeln("	user-select:none;");
document.writeln("}");
document.writeln(".security-help .sh-body em {");
document.writeln("	display:inline-block;");
document.writeln("	position:relative;");
document.writeln("	font-style:normal;");
document.writeln("	white-space:nowrap;");
document.writeln("	text-decoration:underline;");
document.writeln("	cursor:pointer;");
document.writeln("}");
document.writeln("@media (max-width:700px) {");
document.writeln("	.security-help-wrapper {");
document.writeln("	background-color:#fff;");
document.writeln("}");
document.writeln(".security-help .sh-body {");
document.writeln("	font-size:10px;");
document.writeln("}");
document.writeln(".security-help .sh-head {");
document.writeln("	width:110px;");
document.writeln("	min-width:110px;");
document.writeln("	font-size:12px;");
document.writeln("}");
document.writeln(".security-help .sh-head img {");
document.writeln("	width:26px;");
document.writeln("	min-width:26px;");
document.writeln("}");
document.writeln(".bkt {");
document.writeln("	bottom:15px !important;");
document.writeln("}");
document.writeln("}");
document.writeln("</style>");
