// 南通伍林堂文化传播有限公司二维码关注
document.writeln("<div class=\'kz-pc-side-nav\'>");
document.writeln("  <div id=\'qr-code-inner\'>");
document.writeln("    <img src=\'https://1.taoisms.org/daohang/er/yundaojia.png\'>");
document.writeln("    <p>扫描二维码<br>");
document.writeln("      访问云道家小程序");
document.writeln("    </p>");
document.writeln("    <br>");
document.writeln("    <img src=\'https://1.taoisms.org/daohang/er/yundaoshang.png\'>");
document.writeln("    <p>扫描二维码<br>");
document.writeln("      访问云道商小程序");
document.writeln("    </p>");
document.writeln("    <br>");
document.writeln("    <img src=\'https://1.taoisms.org/daohang/er/wulintang.png\'>");
document.writeln("    <p>扫描二维码<br>");
document.writeln("      访问伍林堂小程序");
document.writeln("    </p>");
document.writeln("    <br>");
document.writeln("    <img src=\'https://1.taoisms.org/daohang/er/weixin.png\'>");
document.writeln("    <p>扫描二维码<br>");
document.writeln("      关注伍林堂公众号");
document.writeln("    </p>");
document.writeln("    <br>");
document.writeln("    <img src=\'https://sapi.k780.com/?app=qr.get&amp;data=<?php echo \'http://\'.$_SERVER[\'HTTP_HOST\'].$_SERVER[\'REQUEST_URI\']; ?>&amp;level=H&amp;size=6\'>");
document.writeln("    <p>扫描二维码<br>");
document.writeln("      使用手机访问本站");
document.writeln("    </p>");
document.writeln("  </div>");
document.writeln("</div>");