document.writeln("<style type=text/css>");
document.writeln("@font-face {font-family:huahuaxingkai;src:url(https://www.abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba.cn/ziti/xingkai.ttf);}");
document.writeln(".deng-box {position: fixed;top: -40px;right: -20px;z-index: 9999999;}");
document.writeln(".deng-box1 {position: fixed;top: -30px;right: 10px;z-index: 9999999;}");
document.writeln(".deng-box1 .deng {position: relative;width: 120px;height: 90px;margin: 50px;background: #d8000f;background: rgba(216, 0, 15, 0.9);border-radius: 50% 50%;-webkit-transform-origin: 50% -100px;-webkit-animation: swing 5s infinite ease-in-out;box-shadow: -5px 5px 50px 4px rgba(250, 108, 0, 1);}");
document.writeln(".deng {position: relative;width: 120px;height: 90px;margin: 50px;background: #d8000f;background: rgba(216, 0, 15, 0.9);border-radius: 50% 50%;-webkit-transform-origin: 50% -100px;-webkit-animation: swing 3s infinite ease-in-out;box-shadow: -5px 5px 50px 4px rgba(250, 108, 0, 1);}");
document.writeln(".xian {position: absolute;top: -20px;left: 60px;width: 2px;height: 20px;background: #dc8f03;}");
document.writeln(".deng-a {width: 100px;height: 90px;background: #d8000f;background: rgba(216, 0, 15, 0.2);margin: 12px 8px 8px 8px;border-radius: 50% 50%;border: 2px solid #dc8f03;}");
document.writeln(".deng-b {width: 45px;height: 90px;background: #d8000f;background: rgba(216, 0, 15, 0.2);margin: -4px 8px 8px 26px;border-radius: 50% 50%;border: 2px solid #dc8f03;}");
document.writeln(".shui {width: 5px;height: 40px;background: #ffa500;border-radius: 0 0 5px 5px;}");
document.writeln(".shui-a {margin: -10px 0 0 40px;-webkit-animation: swing 4s infinite ease-in-out;-webkit-transform-origin: 50% -20px;}");
document.writeln(".shui-b {margin: -35px 0 0 59px;-webkit-animation: swing 4s infinite ease-in-out;-webkit-transform-origin: 50% -45px;}");
document.writeln(".shui-c {margin: -45px 0 0 77px;-webkit-animation: swing 4s infinite ease-in-out;-webkit-transform-origin: 50% -25px;}");
document.writeln(".deng:before {position: absolute;top: -7px;left: 29px;height: 12px;width: 60px;content: \' \';display: block;z-index: 999;border-radius: 5px 5px 0 0;border: solid 1px #dc8f03;background: #ffa500;background: linear-gradient(to right, #dc8f03, #ffa500, #dc8f03, #ffa500, #dc8f03);}");
document.writeln(".deng:after {position: absolute;bottom: -7px;left: 10px;height: 12px;width: 60px;content: \' \';display: block;margin-left: 20px;border-radius: 0 0 5px 5px;border: solid 1px #dc8f03;background: #ffa500;background: linear-gradient(to right, #dc8f03, #ffa500, #dc8f03, #ffa500, #dc8f03);}");
document.writeln(".deng-t {font-family:huahuaxingkai!important;font-size: 3.2rem;color: #dc8f03;font-weight: bold;line-height: 85px;text-align: center;}");
document.writeln(".night .deng-t,.night .deng-box,.night .deng-box1 {background: transparent !important;}");
document.writeln("@-moz-keyframes swing {");
document.writeln("0% {-moz-transform: rotate(-10deg)}");
document.writeln("50% {-moz-transform: rotate(10deg)}");
document.writeln("100% {-moz-transform: rotate(-10deg)}");
document.writeln("}");
document.writeln("@-webkit-keyframes swing {");
document.writeln("0% {-webkit-transform: rotate(-10deg)}");
document.writeln("50% {-webkit-transform: rotate(10deg)}");
document.writeln("100% {-webkit-transform: rotate(-10deg)}");
document.writeln("}");
document.writeln("</style>");
document.writeln("<!-- 灯笼 1 -->");
document.writeln("<div class=\'deng-box\'>");
document.writeln("<div class=\'deng\'>");
document.writeln("<div class=\'xian\'></div>")
document.writeln("<div class=\'deng-a\'>");
document.writeln("<div class=\'deng-b\'><div class=\'deng-t\'>节</div></div>");
document.writeln("</div>");
document.writeln("<div class=\'shui shui-a\'></div>");
document.writeln("<div class=\'shui shui-b\'></div>");
document.writeln("<div class=\'shui shui-c\'></div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<!-- 灯笼 2 -->");
document.writeln("<div class=\'deng-box1\'>");
document.writeln("<div class=\'deng\'>");
document.writeln("<div class=\'xian\'></div>")
document.writeln("<div class=\'deng-a\'>");
document.writeln("<div class=\'deng-b\'><div class=\'deng-t\'>春</div></div>");
document.writeln("</div>");
document.writeln("<div class=\'shui shui-a\'></div>");
document.writeln("<div class=\'shui shui-b\'></div>");
document.writeln("<div class=\'shui shui-c\'></div>");
document.writeln("</div>");
document.writeln("</div>");